### ISSUE TITLE
Add plus icon in front of "New Project" in top menu

### ISSUE THREAD

**Issue by ludeknovy** [ludeknovy/jtl-reporter#52]
**Is your feature request related to a problem? Please describe.**
Add plus icon to make it more clear its actionable item and visually distinguish it from project listing in the menu

**Describe the solution you'd like**
Add <i class="fas fa-plus"></i>

**Additional context**
Add it in `add-project-modal` component

**Comment by kamal2222ahmed** [comment]
I apologize for my ignorance, but is there a README.md or steps on how to setup a development environment? since there isn't add-project-modal component, in the source, i am assuming it's i the Docker container jtl-reporter_fe_1
I am also assuming it's React. This will especially good for me as i have just started a Udemy Course on React Development. complete-react-developer-zero-to-mastery
Thanks,

**Comment by ludeknovy** [comment]
The repository for FE is here: https://github.com/ludeknovy/jtl-reporter-fe
Actually its written in Angular ;)

Well, the readme is weak. But to run the FE part you need to fork it, and run in the project root folder:
```
npm install
npm run start
```
Of course you need to have nodejs installed beforehand.

And you most likely will need to run the BE, to pass the auth. 
You can use the dockerized version for it

**Comment by ludeknovy** [comment]
@kamal2222ahmed did you manage to run the FE locally? Do you need any assistance?
